/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/activity/index.vue')['default']
    AddressItem: typeof import('./src/components/addressItem/index.vue')['default']
    ContentTabs: typeof import('./src/components/contentTabs/index.vue')['default']
    HomeTags: typeof import('./src/components/homeTags/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/index.vue')['default']
    Swiper: typeof import('./src/components/swiper/index.vue')['default']
    SwiperSon: typeof import('./src/components/swiperSon/index.vue')['default']
  }
}
